### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by joshtynjala** [Corsaair/markdownlib#1]
I don't see a license anywhere. Is it BSD licensed, like Markdown.pl?

https://daringfireball.net/projects/markdown/license.text

Can you add a license file to the repository?

**Comment by zwetan** [comment]
fixed

followed a basic format of

```
<Your Software is a program that does this and that.>

Copyright 2018 <Your Name>

<Your License text>

---

<Your Software> was ported from <Original Software>:

Copyright 2015 <Original Author Name>

<Original License text>
```

both use the [3-Clause BSD License](https://opensource.org/licenses/BSD-3-Clause)

**Comment by zwetan** [comment]
side note, the library is half working
at the time if I remember well I had some differences in parsing etc.
added some tests but never took/had the time to come back and finish it

**Comment by joshtynjala** [comment]
Thank you!

> side note, the library is half working

Understood. I found a couple others too, so hopefully one of them will meet my needs!
